services:
  mosquitto:
    build:
      args:
        GID: 1000
        UID: 1000
        USER: "marcin"
    user: 1000:1000
#  backend:
#    build:
#      args:
#        GID: 1000
#        UID: 1000
#        USER: "marcin"
#    user: 1000:1000

  celery-beat:
    build:
      args:
        GID: 1000
        UID: 1000
        USER: "marcin"
    user: 1000:1000

  celery-worker:
    build:
      args:
        GID: 1000
        UID: 1000
        USER: "marcin"
    user: 1000:1000

  flower:
    build:
      args:
        GID: 1000
        UID: 1000
        USER: "marcin"
    user: 1000:1000