services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    restart: on-failure
  mosquitto:
    build:
      context: ./mqtt_broker
    volumes:
      - type: bind
        source: ./mqtt_broker/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mqtt_broker/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data"
