FROM python:3.13.3-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1



WORKDIR /app


COPY Pipfile Pipfile.lock ./
RUN pip install --no-cache-dir pipenv  && pipenv install -v --system
COPY . .

EXPOSE 8000


RUN addgroup -S django
RUN adduser -S -G django django
RUN chown -R django /app
RUN chmod -R o+w /app/logs/app.toml
COPY ./entrypoint.sh .

ENTRYPOINT ["./entrypoint.sh"]



