
FROM python:3.11.9-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

ARG UID
ARG GID
ARG USER


WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pip install --no-cache-dir pipenv
RUN pipenv install --system


COPY . .

EXPOSE 8000

RUN if [ ${USER} != "root" ]; then \
    apk add shadow && \
    groupadd -f -g ${GID} ${USER} && \
    useradd -m -g ${USER} -u ${UID} ${USER}; \
    fi


USER ${USER}



CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000
