# Generated by Django 5.2 on 2025-05-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_heater', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageheater',
            options={'ordering': ['-time_stamp']},
        ),
    ]
