# Generated by Django 5.2 on 2025-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_heater', '0002_alter_storageheater_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageheater',
            name='relay_five',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storageheater',
            name='relay_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storageheater',
            name='relay_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storageheater',
            name='relay_six',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storageheater',
            name='relay_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storageheater',
            name='relay_two',
            field=models.BooleanField(default=False),
        ),
    ]
