# Generated by Django 5.2.1 on 2025-10-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_heater', '0003_alter_storageheater_relay_five_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageheater',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='storageheater',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
