# Generated by Django 5.2.1 on 2025-05-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(help_text='Time at which given price starts')),
                ('valid_to', models.DateTimeField(help_text='Time at which given price stops')),
                ('value_inc_vat', models.DecimalField(decimal_places=3, help_text='energy price per kwh, with Vat', max_digits=8, verbose_name='Price per kwh')),
            ],
        ),
    ]
