# Generated by Django 4.1.6 on 2023-02-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPrices',
            fields=[
                ('valid_from', models.DateTimeField(editable=False, help_text='Time at which given price starts', primary_key=True, serialize=False)),
                ('valid_to', models.DateTimeField(editable=False, help_text='Time at which given price stops')),
                ('value_inc_vat', models.DecimalField(decimal_places=2, editable=False, help_text='energy price per kwh, with Vat', max_digits=4, verbose_name='Price per kwh')),
            ],
        ),
    ]
