# Generated by Django 4.1.6 on 2023-02-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnergyPrices',
            new_name='EnergyPrice',
        ),
    ]
