# Generated by Django 4.1.7 on 2023-02-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_prices', '0002_rename_energyprices_energyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyprice',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energyprice',
            name='valid_from',
            field=models.DateTimeField(editable=False, help_text='Time at which given price starts'),
        ),
    ]
