# Generated by Django 4.1.7 on 2023-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_prices', '0003_energyprice_id_alter_energyprice_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyprice',
            name='valid_from',
            field=models.DateTimeField(help_text='Time at which given price starts'),
        ),
        migrations.AlterField(
            model_name='energyprice',
            name='valid_to',
            field=models.DateTimeField(help_text='Time at which given price stops'),
        ),
    ]
