# Generated by Django 4.1.7 on 2023-03-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_prices', '0005_alter_energyprice_value_inc_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyprice',
            name='value_inc_vat',
            field=models.DecimalField(decimal_places=3, help_text='energy price per kwh, with Vat', max_digits=8, verbose_name='Price per kwh'),
        ),
    ]
