# Generated by Django 4.1.7 on 2023-03-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_prices', '0006_alter_energyprice_value_inc_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyprice',
            name='valid_from',
            field=models.DateTimeField(help_text='Time at which given price starts', unique=True),
        ),
        migrations.AlterField(
            model_name='energyprice',
            name='valid_to',
            field=models.DateTimeField(help_text='Time at which given price stops', unique=True),
        ),
    ]
