# Generated by Django 5.1 on 2024-11-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0002_energylog_active_power_a_energylog_active_power_b_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energylog',
            options={'ordering': ['-timestamp']},
        ),
    ]
