# Generated by Django 5.2 on 2025-04-23 12:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0003_alter_energylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='energylog',
            name='device_status',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energylog',
            name='power_factor_a',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='energylog',
            name='power_factor_b',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='energylog',
            name='power_factor_c',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='energylog',
            name='voltage_phase_seq',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
