# Generated by Django 5.2.1 on 2025-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0005_alter_energylog_unit_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energylog',
            name='device_status',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='energylog',
            name='voltage_phase_seq',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
