# Generated by Django 5.2.1 on 2025-05-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_threshold', models.SmallIntegerField(default=2495)),
                ('safe_voltage_threshold', models.SmallIntegerField(default=2460)),
                ('heating_required', models.BooleanField(default=False)),
            ],
        ),
    ]
