# Generated by Django 5.2.1 on 2025-05-29 12:20

from django.db import migrations


def generate_initial_settings(apps, schema_editor):
    from core.models import ProjectSettings

    ProjectSettings.objects.create(
        voltage_threshold=2495,
        safe_voltage_threshold=2460,
        heating_required=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_initial_settings)
    ]
